### ISSUE TITLE
Comments for stitch, fill and padd 

### ISSUE THREAD

**Issue by 4l0n50** [Toposware/certificate-stark#19]
These three functions lack of a short and clear description of inputs and behaviour. I find hard to see what they are doing

https://github.com/Toposware/certificate-stark/blob/64c1962b5d59c4f9e758d8b973829d2e767c3112/src/utils/periodic_columns.rs#L14

https://github.com/Toposware/certificate-stark/blob/64c1962b5d59c4f9e758d8b973829d2e767c3112/src/utils/periodic_columns.rs#L37

https://github.com/Toposware/certificate-stark/blob/64c1962b5d59c4f9e758d8b973829d2e767c3112/src/utils/periodic_columns.rs#L65

**Comment by Nashtare** [comment]
Agreed, let's add some. Perhaps other helper functions as well, for a global better understanding of how this crate works.
